spring:
  datasource:
    url: jdbc:mysql://localhost:3306/iservicesdb?&serverTimezone=UTC
    username: root
    password: senha-segura
    
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true